name: Public Bot Unict

on:
  schedule:
    - cron: '*/6 * * * *' # Gira ogni ora. Puoi cambiare la frequenza qui.
  workflow_dispatch:      # Ti permette di farlo partire a mano premendo "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Versione aggiornata (niente più avvisi gialli!)

      - name: Set up Python
        uses: actions/setup-python@v5 # Versione aggiornata
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add *.txt
          # Il comando seguente evita che il workflow fallisca se non ci sono nuovi avvisi da salvare
          git commit -m "Aggiornamento cronologia avvisi [skip ci]" || exit 0
          git push
